title: Practice Directions
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
section_order:
  - Title B
  - Title A
elastic_search:
  index: pd
  doctype: bare
environment: DEV
server_LOCAL: http://127.0.0.1:3000
server_DEV: https://ec2-13-250-54-121.ap-southeast-1.compute.amazonaws.com
